# Generated by Django 3.2.7 on 2021-10-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='year_of_death',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
