# Generated by Django 3.2.7 on 2021-10-14 12:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poem', '0003_comment_dislike_like'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('user', 'poem')},
        ),
        migrations.AlterUniqueTogether(
            name='dislike',
            unique_together={('user', 'poem')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'poem')},
        ),
    ]
