# Generated by Django 3.2.7 on 2021-10-14 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0004_auto_20211014_1256'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
    ]
