# Generated by Django 3.2.7 on 2021-10-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0005_alter_comment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
